"""Shared day/plan/note/claim/drill/resume/memory/prompt/harness operations.

Barrel re-exporting the subdomain modules so callers keep using
``from gotit.db import ops as day_ops`` and ``day_ops.<name>`` unchanged.
"""

from __future__ import annotations

from gotit.db.ops._common import (
    DEFAULT_USER_ID,
    EXCERPT_LEN,
    _claim_view,
    _excerpt,
    _note_view,
    _plan_item_view,
)
from gotit.db.ops.bootcamp import (
    get_bootcamp_status,
    put_bootcamp_status,
    resolve_bootcamp,
)
from gotit.db.ops.calibration import (
    answer_calibration,
    apply_item_calibration_update,
    get_calibration,
    run_synthetic_calibration,
    start_calibration,
)
from gotit.db.ops.claim import (
    MASTERY_SOURCE_CALIBRATION,
    MASTERY_SOURCE_HARNESS,
    MASTERY_SOURCE_VERIFY,
    apply_examine_verdict,
    list_project_claims,
    list_topic_claims_today,
    set_claim_preferred_check_mode,
    write_mastery_outcome,
)
from gotit.db.ops.connectors import (
    delete_connector,
    get_connector,
    import_connectors,
    list_connectors,
    normalize_connector_config,
    parse_mcp_servers_json,
    set_connector_status,
    update_connector,
    upsert_connector,
)
from gotit.db.ops.day import (
    close_today,
    delete_plan_item,
    ensure_day,
    fill_today_from_queue,
    get_plan,
    get_today,
    list_due_claims,
    update_plan_item,
    upsert_plan_item,
)
from gotit.db.ops.drill import (
    _drill_material_view,
    _drill_session_view,
    append_drill_message,
    create_drill_session,
    delete_drill_material,
    finish_drill_session,
    get_drill_session,
    list_drill_materials,
    list_drill_sessions,
    upsert_drill_material,
)
from gotit.db.ops.evidence import build_evidence_pack_for_claim
from gotit.db.ops.graph import (
    add_depends_on,
    build_budget_subgraph,
    fail_counts_by_claim,
    list_confused_edges,
    list_depends_edges,
    record_verify_mastery_writeback,
    remove_depends_on,
    seed_confused_for_calibration,
)
from gotit.db.ops.harness import (
    _harness_case_view,
    _harness_run_view,
    add_harness_case_result,
    add_harness_run,
    finalize_harness_run,
    get_harness_run,
    list_harness_case_results,
    list_harness_runs,
    set_harness_decision,
)
from gotit.db.ops.identity import (
    get_identity,
    list_identities,
    seed_default_identities,
    upsert_identity,
)
from gotit.db.ops.interview import (
    default_interview_ramp_prefs,
    delete_interview,
    get_interview_ramp_prefs,
    interview_focus_for_today,
    list_due_interview_reminders,
    list_interview_ramp_nudges,
    list_interviews,
    list_upcoming_interviews,
    mark_interview_ramp_nudged,
    mark_interview_reminded,
    patch_interview,
    put_interview_ramp_prefs,
    update_interview_status,
    upsert_interview,
)
from gotit.db.ops.ability_projection import build_ability_state
from gotit.db.ops.companion_state import build_companion_state_brief
from gotit.db.ops.learner_state import build_learner_state
from gotit.db.ops.next_action import build_next_action
from gotit.db.ops.memory import (
    _memory_view,
    add_memory,
    append_trajectory,
    build_failure_lesson_block,
    count_prior_failures,
    failure_hints_by_claim,
    failure_writeback_and_lessons,
    list_memory,
    list_pending_failure_digests,
    list_trajectory,
    mark_failure_digest_notified,
    maybe_record_failure_digest,
    prior_failure_counts_by_claim,
    trajectory_has_idempotency_key,
)
from gotit.db.ops.note import (
    _strip_html,
    add_note,
    curate_claims,
    delete_note,
    delete_notes,
    get_note,
    ingest_note,
    list_all_notes,
    list_note_claims,
    list_notes,
    list_project_notes,
    stub_extract_claim,
)
from gotit.db.ops.project import (
    _project_view,
    archive_project,
    create_project,
    get_project,
    list_projects,
    project_progress,
    update_project,
)
from gotit.db.ops.prompt import (
    _prompt_view,
    get_active_prompt,
    list_prompts,
    register_prompts,
)
from gotit.db.ops.resume import (
    _resume_pk,
    _resume_view,
    apply_resume,
    get_resume,
    upsert_resume,
)
from gotit.db.ops.shell import (
    build_graph_v0,
    build_profile_v0,
    claim_reject_reason,
    default_digest_prefs,
    delete_shell_activity,
    delete_shell_activity_many,
    get_digest_prefs,
    interest_material,
    list_shell_activity,
    promote_interest,
    put_digest_prefs,
    record_interest,
    record_shell_event,
    sync_digest_openclaw_cron,
)
from gotit.db.ops.skills import (
    delete_user_skill,
    get_skill_detail,
    install_skill,
    list_skill_catalog,
    parse_skill_markdown,
    resolve_skill_body,
    set_skill_enabled,
    update_skill_markdown,
)
from gotit.db.ops.thread import (
    PLACEHOLDER_THREAD_TITLES,
    add_message,
    append_workflow_exchange,
    clear_ball,
    count_user_messages,
    create_thread,
    delete_thread,
    derive_thread_title,
    get_ball,
    get_thread,
    list_messages,
    list_threads,
    maybe_retitle_placeholder_thread,
    set_ball,
    touch_thread,
    update_thread_title,
)

__all__ = [
    "DEFAULT_USER_ID",
    "EXCERPT_LEN",
    # private helpers re-exported for legacy `day_ops._<name>` callers
    "_claim_view",
    "_excerpt",
    "_note_view",
    "_plan_item_view",
    "_drill_material_view",
    "_drill_session_view",
    "_harness_case_view",
    "_harness_run_view",
    "_memory_view",
    "_project_view",
    "_prompt_view",
    "_resume_pk",
    "_resume_view",
    "_strip_html",
    # day / plan / chat
    "ensure_day",
    "get_plan",
    "upsert_plan_item",
    "update_plan_item",
    "delete_plan_item",
    "list_due_claims",
    "fill_today_from_queue",
    "get_today",
    "close_today",
    # note / ingest
    "add_note",
    "list_notes",
    "list_all_notes",
    "get_note",
    "delete_note",
    "delete_notes",
    "stub_extract_claim",
    "ingest_note",
    "curate_claims",
    "list_note_claims",
    "list_project_notes",
    # claim / examine
    "apply_examine_verdict",
    "write_mastery_outcome",
    "MASTERY_SOURCE_VERIFY",
    "MASTERY_SOURCE_CALIBRATION",
    "MASTERY_SOURCE_HARNESS",
    "list_topic_claims_today",
    "list_project_claims",
    "set_claim_preferred_check_mode",
    # first-pass bootcamp
    "get_bootcamp_status",
    "put_bootcamp_status",
    "resolve_bootcamp",
    # cold-start calibration
    "start_calibration",
    "answer_calibration",
    "get_calibration",
    "run_synthetic_calibration",
    "apply_item_calibration_update",
    # project
    "create_project",
    "list_projects",
    "get_project",
    "update_project",
    "archive_project",
    "project_progress",
    # resume
    "upsert_resume",
    "get_resume",
    "apply_resume",
    # drill
    "list_drill_materials",
    "upsert_drill_material",
    "delete_drill_material",
    "create_drill_session",
    "append_drill_message",
    "finish_drill_session",
    "list_drill_sessions",
    "get_drill_session",
    # interviews (companion-os P3d + P4 ramp)
    "list_interviews",
    "upsert_interview",
    "patch_interview",
    "update_interview_status",
    "delete_interview",
    "list_due_interview_reminders",
    "mark_interview_reminded",
    "list_upcoming_interviews",
    "list_interview_ramp_nudges",
    "mark_interview_ramp_nudged",
    "get_interview_ramp_prefs",
    "put_interview_ramp_prefs",
    "default_interview_ramp_prefs",
    "interview_focus_for_today",
    # prompt
    "register_prompts",
    "get_active_prompt",
    "list_prompts",
    # memory
    "add_memory",
    "list_memory",
    "append_trajectory",
    "list_trajectory",
    "count_prior_failures",
    "trajectory_has_idempotency_key",
    "prior_failure_counts_by_claim",
    "maybe_record_failure_digest",
    "list_pending_failure_digests",
    "mark_failure_digest_notified",
    "build_failure_lesson_block",
    "build_evidence_pack_for_claim",
    "build_learner_state",
    "build_ability_state",
    "build_next_action",
    "build_companion_state_brief",
    "failure_hints_by_claim",
    "failure_writeback_and_lessons",
    # shell / obs (OpenClaw bridge)
    "record_shell_event",
    "record_interest",
    "promote_interest",
    "claim_reject_reason",
    "interest_material",
    "list_shell_activity",
    "delete_shell_activity",
    "delete_shell_activity_many",
    "get_digest_prefs",
    "put_digest_prefs",
    "default_digest_prefs",
    "sync_digest_openclaw_cron",
    "build_profile_v0",
    "build_graph_v0",
    # mastery graph
    "record_verify_mastery_writeback",
    "build_budget_subgraph",
    "fail_counts_by_claim",
    "list_confused_edges",
    "list_depends_edges",
    "add_depends_on",
    "remove_depends_on",
    "seed_confused_for_calibration",
    # harness
    "add_harness_run",
    "add_harness_case_result",
    "finalize_harness_run",
    "get_harness_run",
    "set_harness_decision",
    "list_harness_runs",
    "list_harness_case_results",
    # identity
    "upsert_identity",
    "get_identity",
    "list_identities",
    "seed_default_identities",
    # thread / message / ball custody
    "create_thread",
    "list_threads",
    "get_thread",
    "update_thread_title",
    "touch_thread",
    "delete_thread",
    "PLACEHOLDER_THREAD_TITLES",
    "derive_thread_title",
    "maybe_retitle_placeholder_thread",
    "add_message",
    "append_workflow_exchange",
    "count_user_messages",
    "list_messages",
    "get_ball",
    "set_ball",
    "clear_ball",
    # skills / connectors (profile center)
    "list_skill_catalog",
    "get_skill_detail",
    "resolve_skill_body",
    "install_skill",
    "update_skill_markdown",
    "set_skill_enabled",
    "delete_user_skill",
    "parse_skill_markdown",
    "list_connectors",
    "get_connector",
    "upsert_connector",
    "update_connector",
    "set_connector_status",
    "delete_connector",
    "import_connectors",
    "normalize_connector_config",
    "parse_mcp_servers_json",
]
